### PR TITLE
thunderbird-nightly-bin: Add group policy to disable app updates

### PR DESCRIPTION
**Pull request by benjamb**
As per the suggestion of bmd_online and blackout on the aur, disable thunderbirds update notifications.

### CODE REVIEW

**Comment by freswa** [comment]
I think this should at least be optional. As this is a nightly build some people might want to be notified when a new version is available. Is there another way to disable updates? E.g. via some file in `~/.thunderbird` maybe?

**Comment by benjamb** [comment]
Aye, fair enough. Unfortunately `policies.json` can only go within a `distribution/` directory in the installation directory, I've failed to find another way of disabling it.

Could I perhaps modify this patch so that the version is stripped from the path in /opt such that if I place one here by hand locally it will remain effective across updates?

**Comment by benjamb** [comment]
@freswa Any thoughts on stripping the version from the install dir, such that the path remains consistent across updates?

**Comment by freswa** [comment]
I don't see it in this PR. What would be the benefit?

**Comment by benjamb** [comment]
@freswa It's not at the moment, because I was trying to include the policy to disable app update notifications via `policies.json`, but couldn't find a way to do this outside of the installation directory. By instead updating this PR such that the installation paths remain consistent, I can then manually write a `policies.json` and not worry about having to recreate/move it on every thunderbird-nightly update.

**Comment by benjamb** [comment]
@freswa Thanks for that. Just attempted to install the noupdate package, but I get the following error:
```
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: thunderbird-nightly-bin and thunderbird-nightly-bin-noupdate are in conflict
```

**Comment by freswa** [comment]
Should be fixed now.

**Pull request closed without merging**
